name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./server/config.ini:/config.ini
    networks:
      - testing_net
      
  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - CLI_NAME=Santiago Lionel
      - CLI_SURNAME=Lorca
      - CLI_DNI=30904465
      - CLI_BIRTHDAY=1990-01-01
      - CLI_LOTTERYNUM=4263
    volumes:
      - ./client/config.yaml:/config.yaml
    networks:
      - testing_net
    depends_on:
      - server

  client2:
    container_name: client2
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=2
      - CLI_NAME=Facundo
      - CLI_SURNAME=Huttin
      - CLI_DNI=43746167
      - CLI_BIRTHDAY=2001-01-01
      - CLI_LOTTERYNUM=3942
    volumes:
      - ./client/config.yaml:/config.yaml
    networks:
      - testing_net
    depends_on:
      - server

  client3:
    container_name: client3
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=3
      - CLI_NAME=Maria
      - CLI_SURNAME=Gonzalez
      - CLI_DNI=12345678
      - CLI_BIRTHDAY=1985-05-15
      - CLI_LOTTERYNUM=5678
    volumes:
      - ./client/config.yaml:/config.yaml
    networks:
      - testing_net
    depends_on:
      - server

  client4:
    container_name: client4
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=4
      - CLI_NAME=Juan
      - CLI_SURNAME=Martinez
      - CLI_DNI=87654321
      - CLI_BIRTHDAY=1992-07-20
      - CLI_LOTTERYNUM=1234
    volumes:
      - ./client/config.yaml:/config.yaml
    networks:
      - testing_net
    depends_on:
      - server

  client5:
    container_name: client5
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=5
      - CLI_NAME=Ana
      - CLI_SURNAME=Rodriguez
      - CLI_DNI=23456789
      - CLI_BIRTHDAY=1988-03-10
      - CLI_LOTTERYNUM=7890
    volumes:
      - ./client/config.yaml:/config.yaml
    networks:
      - testing_net
    depends_on:
      - server

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
